import { initClickCtaTop } from "./trackers/click_cta_top.js";
import { initClickCtaBottom } from "./trackers/click_cta_bottom.js";
import { initExternalLinkRaid  } from "./trackers/external_link_raid.js";
import { initScrollDepth } from "./trackers/scroll_depth.js";
import { initExternalLinkOurRaids } from "./trackers/external_link_our_raids.js";
import { initExternalLinkDetails } from "./trackers/external_link_details.js";
import { initGalleryTeachersScroll } from "./trackers/gallery_teachers_scroll.js";
import { initExternalLinkMentorPage } from "./trackers/external_link_mentor_page.js";
import { initExternalLinkSocial } from "./trackers/external_link_social.js";
import { initClickLinksBuyAccess } from "./trackers/click_links_buy_access.js";
import { initFaqOpenAnswer } from "./trackers/faq_open_answer.js";
import { initClickLinksTelegram } from "./trackers/click_links_telegram.js";
import { initClickLinksYoutubeEntertainment } from "./trackers/click_links_youtube_entertainment.js";
import { initClickLinksYoutubeStreams } from "./trackers/click_links_youtube_streams.js";
import { initClickLinksTiktok } from "./trackers/click_links_tiktok.js";
import { initClickLinksInstagram } from "./trackers/click_links_instagram.js";
import { initClickLinksArtstation } from "./trackers/click_links_artstation.js";
import { initClickLinks3dGuide } from "./trackers/click_links_3d_guide.js";
import { initGalleryRaidsScroll } from "./trackers/gallery_raids_scroll.js";

(function(){
  initClickCtaTop();
  initClickCtaBottom();
  initExternalLinkRaid ();
  initScrollDepth();
  initExternalLinkOurRaids();
  initExternalLinkDetails();
  initGalleryTeachersScroll();
  initExternalLinkMentorPage();
  initExternalLinkSocial();
  initClickLinksBuyAccess();
  initFaqOpenAnswer();
  initClickLinksTelegram();
  initClickLinksYoutubeEntertainment();
  initClickLinksYoutubeStreams();
  initClickLinksTiktok();
  initClickLinksInstagram();
  initClickLinksArtstation();
  initClickLinks3dGuide();
  initGalleryRaidsScroll();
})();